openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/RaphaelPletz/momolita-game/1.0.0
info:
  description: This is an API that receives bug and player reports for an imaginary game called Momolita
  version: "1.0.0"
  title: Momolita reporting system
  contact:
    email: raphael.pletz00@gmail.com
tags:
  - name: Bugs
    description: In-game or website bugs reporting
  - name: Player reporting
    description: Abusive players reporting
paths:
  /reports/bugs:
    post:
      tags:
        - Bugs
      summary: Report a newfound bug
      operationId: app.add_bug_report
      description: Adds a new bug to the system
      responses:
        '201':
          description: Bug reported
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bugReport'
        description: Bug report description
  /reports/player:
    post:
      tags:
        - Player reporting
      summary: Report an abusive player
      operationId: app.add_player_report
      description: Adds a new reported player to the system
      responses:
        '201':
          description: Player reported
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/playerReport'
        description: Player report description
components:
  schemas:
    bugReport:
      type: object
      required:
        - title
        - description
        - location
        - type
      properties:
        title:
          type: string
          example: Unable to buy Health Potion
        description:
          type: string
          example: If I double click the second menu option I can't buy the item
        location:
          type: string
          example: Frozen Wastes
          enum: ['Frozen Wastes', 'Golden Sands', 'Death Swamp']
        type:
          type: string
          example: UI
          enum: ['UI', 'Graphics', 'Audio', 'Text', 'Crashing']
        date:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
    playerReport:
      type: object
      required:
        - player_name
        - description
        - location
        - type
      properties:
        player_name:
          type: string
          example: DeathstalkerXXX
        description:
          type: string
          example: The player is flying and killing people instantly
        location:
          type: string
          example: Golden Sands
          enum: ['Frozen Wastes', 'Golden Sands', 'Death Swamp']
        type:
          type: string
          example: 'Hacking'
          enum: ['Griefing', 'Hate Speech', 'Hacking']
        date:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'